name: Python Package using Conda

on: [push]

jobs:
  example-1:
    name: Conda (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.11"]
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Install dependencies
        run: |
          conda install -c conda-forge lapack numba pytest ruff scipy
          python -m pip install --upgrade pip
          pwd
          ls
          cd ..
          pwd
          ls
      #     python -m pip install .
      # - name: Lint with Ruff
      #   run: |
      #     ruff --output-format=github .
      #   continue-on-error: true
      # - name: Test with pytest
      #   run: |
      #     pytest
